# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-19 12:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('my_birthday', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Birthday',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='date')),
                ('last_updated', models.DateTimeField(verbose_name='last updated')),
            ],
        ),
        migrations.RemoveField(
            model_name='person',
            name='birthdate',
        ),
        migrations.AddField(
            model_name='person',
            name='birthday',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='my_birthday.Birthday'),
            preserve_default=False,
        ),
    ]
